/** @type {import('tailwindcss').Config} */
module.exports = {
  // NOTE: Update this to include the paths to all of your component files.
  content: ["./App.{js,jsx,ts,tsx}", "./src/**/*.{js,jsx,ts,tsx}"],
  presets: [require("nativewind/preset")],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        // Vintage Minimalist Named Tokens
        paper: "#F4EFE4",
        "paper-surface": "#FBF8F1",
        ink: "#2B2621",
        "ink-muted": "#6E6459",
        hairline: "#D9CEB9",
        espresso: "#1B1712",
        "espresso-surface": "#241F19",
        bone: "#EDE4D3",
        "bone-muted": "#A89A85",
        "hairline-dark": "#3B3327",
        "stamp-red": "#B23A2E",
        "stamp-olive": "#6E7A54",

        // Semantic Tokens (Default Light, paired with dark: classes)
        background: "#F4EFE4",
        surface: "#FBF8F1",
        "surface-container": "#F2EDE2",
        "surface-container-low": "#F8F3E8",
        "surface-container-high": "#EDE8DD",
        "surface-container-lowest": "#FBF8F1",
        primary: "#2B2621",
        "on-primary": "#F4EFE4",
        secondary: "#6E6459",
        "on-secondary": "#FBF8F1",
        border: "#D9CEB9",
        outline: "#7E766E",
        "outline-variant": "#D9CEB9",
        error: "#B23A2E",
        "on-error": "#FFFFFF",
      },
      fontFamily: {
        display: ["Fraunces_600SemiBold", "serif"],
        "display-medium": ["Fraunces_500Medium", "serif"],
        "display-regular": ["Fraunces_400Regular", "serif"],
        body: ["Inter_400Regular", "sans-serif"],
        "body-medium": ["Inter_500Medium", "sans-serif"],
        "body-semibold": ["Inter_600SemiBold", "sans-serif"],
        "body-bold": ["Inter_700Bold", "sans-serif"],
        mono: ["IBMPlexMono_400Regular", "monospace"],
        "mono-medium": ["IBMPlexMono_500Medium", "monospace"],
        "mono-bold": ["IBMPlexMono_700Bold", "monospace"],
      },
      borderWidth: {
        DEFAULT: "1px",
        hairline: "1px",
      },
      borderRadius: {
        none: "0px",
        sm: "2px",
        DEFAULT: "4px",
        md: "4px",
        lg: "6px",
        xl: "8px",
        full: "9999px",
      },
      spacing: {
        "stack-sm": "8px",
        "stack-md": "16px",
        "stack-lg": "32px",
        "margin-page": "20px",
        "gutter-grid": "16px",
        "touch-target": "48px",
      },
    },
  },
  plugins: [],
};
