/** @type {import('tailwindcss').Config} */
module.exports = {
  // NOTE: Update this to include the paths to all of your component files.
  content: ["./App.{js,jsx,ts,tsx}", "./src/**/*.{js,jsx,ts,tsx}"],
  presets: [require("nativewind/preset")],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        // Navy Vintage Named Tokens
        paper: "#E6E8EC",
        "paper-surface": "#EFF1F4",
        ink: "#1A2030",
        "ink-muted": "#5C6478",
        hairline: "#C9CDD6",
        espresso: "#12161F",
        "espresso-surface": "#1B2030",
        bone: "#E6E8EC",
        "bone-muted": "#8C93A6",
        "hairline-dark": "#2A3145",
        "stamp-red": "#B23A2E",
        "stamp-olive": "#4F7566",

        // Semantic Tokens (Default Light, paired with dark: classes)
        background: "#E6E8EC",
        surface: "#EFF1F4",
        "surface-container": "#E6E8EC",
        "surface-container-low": "#ECEEF2",
        "surface-container-high": "#E0E3E8",
        "surface-container-lowest": "#EFF1F4",
        primary: "#1A2030",
        "on-primary": "#E6E8EC",
        secondary: "#5C6478",
        "on-secondary": "#EFF1F4",
        border: "#C9CDD6",
        outline: "#5C6478",
        "outline-variant": "#C9CDD6",
        error: "#B23A2E",
        "on-error": "#FFFFFF",
      },
      fontFamily: {
        display: ["Fraunces_600SemiBold", "serif"],
        "display-medium": ["Fraunces_500Medium", "serif"],
        "display-regular": ["Fraunces_400Regular", "serif"],
        body: ["Inter_400Regular", "sans-serif"],
        "body-medium": ["Inter_500Medium", "sans-serif"],
        "body-semibold": ["Inter_600SemiBold", "sans-serif"],
        "body-bold": ["Inter_700Bold", "sans-serif"],
        mono: ["IBMPlexMono_400Regular", "monospace"],
        "mono-medium": ["IBMPlexMono_500Medium", "monospace"],
        "mono-bold": ["IBMPlexMono_700Bold", "monospace"],
      },
      borderWidth: {
        DEFAULT: "1px",
        hairline: "1px",
      },
      borderRadius: {
        none: "0px",
        sm: "2px",
        DEFAULT: "4px",
        md: "4px",
        lg: "6px",
        xl: "8px",
        full: "9999px",
      },
      spacing: {
        "stack-sm": "8px",
        "stack-md": "16px",
        "stack-lg": "32px",
        "margin-page": "20px",
        "gutter-grid": "16px",
        "touch-target": "48px",
      },
    },
  },
  plugins: [],
};
